_wandb:
    value:
        cli_version: 0.22.3
        e:
            8d4g25g8f8hyl14lo73q1vg221tvy40t:
                args:
                    - --BATCH_SIZE=64
                    - --EPOCHS=35
                    - --LR=0.0006535887347790876
                    - --d_model=128
                    - --nhead=4
                    - --num_layers=3
                codePath: Transformer/sweeptrain.py
                codePathLocal: sweeptrain.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "470306373632"
                        used: "358359879680"
                email: autoshin0322@gmail.com
                executable: /home/stud_homes/s6010479/miniconda3/envs/posevit/bin/python
                git:
                    commit: 03a764b947f3d86c3e33c545687437df5401b9e8
                    remote: git@github.com:autoshin0322/Jayproject.git
                gpu: NVIDIA L40S
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-e7f1f5b8-1a9d-63f0-052b-fae92945af2d
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-1dc5f49e-6090-bcb7-f5ff-fdc4840fd9a2
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-5f486164-f234-bb1b-76f9-ede52cbbc994
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-8a0db40c-5f9f-c1a6-8854-4592d8651f49
                host: gondor
                memory:
                    total: "202309451776"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.39
                program: /home/stud_homes/s6010479/Jayproject/Transformer/sweeptrain.py
                python: CPython 3.10.18
                root: /home/stud_homes/s6010479/Jayproject/Transformer
                startedAt: "2025-11-06T21:25:01.334148Z"
                writerId: 8d4g25g8f8hyl14lo73q1vg221tvy40t
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
                - 62
            "4": 3.10.18
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
BATCH_SIZE:
    value: 64
EPOCHS:
    value: 35
LR:
    value: 0.0006535887347790876
d_model:
    value: 128
nhead:
    value: 4
num_layers:
    value: 3
